### PR TITLE
Add new version: alpha number 10

### PR DESCRIPTION
**Pull request by JulienBreux**
Hi,

This is the modification for the new version :)

Have a nice day|nite|life.

### CODE REVIEW

**Comment by Seldaek** [comment]
I don't know why I have access to this repo but I do so merging :P thanks

**Comment by JulienBreux** [comment]
My pleasure, I don't have the access to update build :-/ But thanks for merging.

(https://registry.hub.docker.com/u/composer/composer/builds_history/73087/)

**Comment by RobLoach** [comment]
Haha, awesome, thanks guys! Added the Docker tag, and triggered a build.

**Comment by JulienBreux** [comment]
@RobLoach thanks!

**Pull request merged**
